export const types = [
    "display-lg",
    "display-md",
    "display-sm",
    "title-2xl",
    "title-xl",
    "title-lg",
    "title-md",
    "title-sm",
    "title-xs",
    "body-lg",
    "body-md",
    "body-sm",
    "caption-lg",
    "caption-md",
    "label-lg",
    "label-md",
    "label-sm",
    "label-xs",
];

export const xxlSize = {
    "display-lg": {
        family: "WalledSemiBold",
        size: "72px",
        lineHeight: "100px",
        letterSpacing: "-1.5px",
    },
    "display-md": {
        family: "WalledSemiBold",
        size: "64px",
        lineHeight: "88px",
        letterSpacing: "-1.5px",
    },
    "display-sm": {
        family: "WalledSemiBold",
        size: "56px",
        lineHeight: "80px",
        letterSpacing: "-1.5px",
    },
    "title-2xl": {
        family: "WalledSemiBold",
        size: "48px",
        lineHeight: "68px",
        letterSpacing: "-1px",
    },
    "title-xl": {
        family: "WalledSemiBold",
        size: "42px",
        lineHeight: "60px",
        letterSpacing: "-1px",
    },
    "title-lg": {
        family: "WalledSemiBold",
        size: "36px",
        lineHeight: "52px",
        letterSpacing: "-1px",
    },
    "title-md": {
        family: "WalledSemiBold",
        size: "28px",
        lineHeight: "40px",
        letterSpacing: "-0.5px",
    },
    "title-sm": {
        family: "WalledSemiBold",
        size: "24px",
        lineHeight: "32px",
        letterSpacing: "-0.5px",
    },
    "title-xs": {
        family: "WalledSemiBold",
        size: "22px",
        lineHeight: "32px",
        letterSpacing: "-0.5px",
    },
    "body-lg": {
        family: "WalledRegular",
        size: "24px",
        lineHeight: "36px",
        letterSpacing: "0px",
    },
    "body-md": {
        family: "WalledRegular",
        size: "22px",
        lineHeight: "32px",
        letterSpacing: "0px",
    },
    "body-sm": {
        family: "WalledRegular",
        size: "18px",
        lineHeight: "28px",
        letterSpacing: "0px",
    },
    "caption-lg": {
        family: "WalledSemiBold",
        size: "18px",
        lineHeight: "28px",
        letterSpacing: "0px",
    },
    "label-lg": {
        family: "WalledBold",
        size: "24px",
        lineHeight: "36px",
        letterSpacing: "0px",
    },
    "label-md": {
        family: "WalledBold",
        size: "22px",
        lineHeight: "32px",
        letterSpacing: "0px",
    },
    "label-xs": {
        family: "WalledBold",
        size: "18px",
        lineHeight: "28px",
        letterSpacing: "0px",
    },
};

export const xlSize = {
    "display-lg": {
        family: "WalledSemiBold",
        size: "64px",
        lineHeight: "88px",
        letterSpacing: "-1.5px",
    },
    "display-md": {
        family: "WalledSemiBold",
        size: "56px",
        lineHeight: "80px",
        letterSpacing: "-1.5px",
    },
    "display-sm": {
        family: "WalledSemiBold",
        size: "48px",
        lineHeight: "68px",
        letterSpacing: "-1.5px",
    },
    "title-2xl": {
        family: "WalledSemiBold",
        size: "36px",
        lineHeight: "52px",
        letterSpacing: "-1px",
    },
    "title-xl": {
        family: "WalledSemiBold",
        size: "32px",
        lineHeight: "44px",
        letterSpacing: "-1px",
    },
    "title-lg": {
        family: "WalledSemiBold",
        size: "28px",
        lineHeight: "40px",
        letterSpacing: "-1px",
    },
    "title-md": {
        family: "WalledSemiBold",
        size: "22px",
        lineHeight: "32px",
        letterSpacing: "-0.5px",
    },
    "title-sm": {
        family: "WalledSemiBold",
        size: "18px",
        lineHeight: "24px",
        letterSpacing: "-0.5px",
    },
    "title-xs": {
        family: "WalledSemiBold",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "-0.5px",
    },
    "body-lg": {
        family: "WalledRegular",
        size: "18px",
        lineHeight: "28px",
        letterSpacing: "0px",
    },
    "body-md": {
        family: "WalledRegular",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "body-sm": {
        family: "WalledRegular",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "caption-lg": {
        family: "WalledSemiBold",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "label-lg": {
        family: "WalledBold",
        size: "18px",
        lineHeight: "28px",
        letterSpacing: "0px",
    },
    "label-md": {
        family: "WalledBold",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "label-xs": {
        family: "WalledBold",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
};

export const lgSize = {
    "display-lg": {
        family: "WalledSemiBold",
        size: "56px",
        lineHeight: "80px",
        letterSpacing: "-1.5px",
    },
    "display-md": {
        family: "WalledSemiBold",
        size: "48px",
        lineHeight: "68px",
        letterSpacing: "-1.5px",
    },
    "display-sm": {
        family: "WalledSemiBold",
        size: "40px",
        lineHeight: "56px",
        letterSpacing: "-1.5px",
    },
    "title-2xl": {
        family: "WalledSemiBold",
        size: "32px",
        lineHeight: "44px",
        letterSpacing: "-1px",
    },
    "title-xl": {
        family: "WalledSemiBold",
        size: "28px",
        lineHeight: "40px",
        letterSpacing: "-1px",
    },
    "title-lg": {
        family: "WalledSemiBold",
        size: "24px",
        lineHeight: "32px",
        letterSpacing: "-1px",
    },
    "title-md": {
        family: "WalledSemiBold",
        size: "20px",
        lineHeight: "28px",
        letterSpacing: "-0.5px",
    },
    "title-sm": {
        family: "WalledSemiBold",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "-0.5px",
    },
    "title-xs": {
        family: "WalledSemiBold",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "-0.5px",
    },
    "body-lg": {
        family: "WalledRegular",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "body-md": {
        family: "WalledRegular",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "body-sm": {
        family: "WalledRegular",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "caption-lg": {
        family: "WalledSemiBold",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "label-lg": {
        family: "WalledBold",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "label-md": {
        family: "WalledBold",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "label-xs": {
        family: "WalledBold",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
};

 export const mdSize = {
    "display-lg": {
        family: "WalledSemiBold",
        size: "48px",
        lineHeight: "68px",
        letterSpacing: "-1.5px",
    },
    "display-md": {
        family: "WalledSemiBold",
        size: "40px",
        lineHeight: "56px",
        letterSpacing: "-1.5px",
    },
    "display-sm": {
        family: "WalledSemiBold",
        size: "32px",
        lineHeight: "44px",
        letterSpacing: "-1.5px",
    },
    "title-2xl": {
        family: "WalledSemiBold",
        size: "32px",
        lineHeight: "44px",
        letterSpacing: "-1px",
    },
    "title-xl": {
        family: "WalledSemiBold",
        size: "28px",
        lineHeight: "40px",
        letterSpacing: "-1px",
    },
    "title-lg": {
        family: "WalledSemiBold",
        size: "24px",
        lineHeight: "32px",
        letterSpacing: "-1px",
    },
    "title-md": {
        family: "WalledSemiBold",
        size: "20px",
        lineHeight: "28px",
        letterSpacing: "-0.5px",
    },
    "title-sm": {
        family: "WalledSemiBold",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "-0.5px",
    },
    "title-xs": {
        family: "WalledSemiBold",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "-0.5px",
    },
    "body-lg": {
        family: "WalledRegular",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "body-md": {
        family: "WalledRegular",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "body-sm": {
        family: "WalledRegular",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "caption-lg": {
        family: "WalledSemiBold",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "label-lg": {
        family: "WalledBold",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "label-md": {
        family: "WalledBold",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "label-xs": {
        family: "WalledBold",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
};

export const smSize = {
    "display-lg": {
        family: "WalledSemiBold",
        size: "40px",
        lineHeight: "56px",
        letterSpacing: "-1.5px",
    },
    "display-md": {
        family: "WalledSemiBold",
        size: "32px",
        lineHeight: "44px",
        letterSpacing: "-1.5px",
    },
    "display-sm": {
        family: "WalledSemiBold",
        size: "28px",
        lineHeight: "40px",
        letterSpacing: "-1.5px",
    },
    "title-2xl": {
        family: "WalledSemiBold",
        size: "28px",
        lineHeight: "40px",
        letterSpacing: "-0.5px",
    },
    "title-xl": {
        family: "WalledSemiBold",
        size: "24px",
        lineHeight: "32px",
        letterSpacing: "-0.5px",
    },
    "title-lg": {
        family: "WalledSemiBold",
        size: "22px",
        lineHeight: "32px",
        letterSpacing: "-0.5px",
    },
    "title-md": {
        family: "WalledSemiBold",
        size: "20px",
        lineHeight: "28px",
        letterSpacing: "0px",
    },
    "title-sm": {
        family: "WalledSemiBold",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "title-xs": {
        family: "WalledSemiBold",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "body-lg": {
        family: "WalledRegular",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "body-md": {
        family: "WalledRegular",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "body-sm": {
        family: "WalledRegular",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "caption-lg": {
        family: "WalledSemiBold",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "label-lg": {
        family: "WalledBold",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "label-md": {
        family: "WalledBold",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "label-xs": {
        family: "WalledBold",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
};

export const xsSize = {
    "display-lg": {
        family: "WalledSemiBold",
        size: "32px",
        lineHeight: "44px",
        letterSpacing: "-0.5px",
    },
    "display-md": {
        family: "WalledSemiBold",
        size: "28px",
        lineHeight: "40px",
        letterSpacing: "-0.5px",
    },
    "display-sm": {
        family: "WalledSemiBold",
        size: "24px",
        lineHeight: "32px",
        letterSpacing: "0px",
    },
    "title-2xl": {
        family: "WalledSemiBold",
        size: "24px",
        lineHeight: "32px",
        letterSpacing: "0px",
    },
    "title-xl": {
        family: "WalledSemiBold",
        size: "22px",
        lineHeight: "32px",
        letterSpacing: "0px",
    },
    "title-lg": {
        family: "WalledSemiBold",
        size: "20px",
        lineHeight: "28px",
        letterSpacing: "0px",
    },
    "title-md": {
        family: "WalledSemiBold",
        size: "18px",
        lineHeight: "28px",
        letterSpacing: "0px",
    },
    "title-sm": {
        family: "WalledSemiBold",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "title-xs": {
        family: "WalledSemiBold",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "body-lg": {
        family: "WalledRegular",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "body-md": {
        family: "WalledRegular",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "body-sm": {
        family: "WalledRegular",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "caption-lg": {
        family: "WalledSemiBold",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "label-lg": {
        family: "WalledBold",
        size: "16px",
        lineHeight: "24px",
        letterSpacing: "0px",
    },
    "label-md": {
        family: "WalledBold",
        size: "14px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
    "label-xs": {
        family: "WalledBold",
        size: "12px",
        lineHeight: "20px",
        letterSpacing: "0px",
    },
};

export const breakpoints = {
    xxl: "3840px",
    xl: "2559px",
    lg: "1919px",
    md: "1439px",
    sm: "1023px",
    xs: "767px",
};